server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: validate
          uri: ${VALIDATE_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/validate/**

        - id: auth-v1-explicit
          uri: ${AUTH_SERVICE_V1_URL:http://localhost:8082}
          predicates:
            - Path=/auth/v1/**
          filters:
            - RewritePath=/auth/v1/(?<segment>.*), /auth/$\{segment}

        - id: auth-v2
          uri: ${AUTH_SERVICE_V2_URL:http://localhost:8085}
          predicates:
            - Path=/auth/v2/**
          filters:
            - RewritePath=/auth/v2/(?<segment>.*), /auth/$\{segment}

        - id: auth-v1-legacy
          uri: ${AUTH_SERVICE_V1_URL:http://localhost:8082}
          predicates:
            - Path=/auth/**

        - id: signer
          uri: ${SIGNER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/sign/**
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

app:
  rate-limit:
    capacity: 60
    window: 1m

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
